name: build-image-wild

on:
  schedule:
    - cron:  '0 0,8,16 * * *'
  push:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

  pull_request:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

  workflow_dispatch:

jobs:
  build:
    uses: hero-intelligent/docker-node/.github/workflows/docker-build.yml@main
    with:
      node_version: [18,20]
      base_image: [alpine3.17,alpine3.18,bookworm-slim,bookworm,bullseye-slim,bullseye]
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASS }}


















  #
  # build:
  #   needs: gen-matrix
  #   name: build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 180
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ needs.gen-matrix.outputs.matrix }}
  #
  #   steps:
  #
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       # id: buildx
  #
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #
  #     - name: Login to Docker Hub
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASS }}
  #
  #     - name: Build image
  #       uses: docker/build-push-action@v5
  #       with:
  #         builder: ${{ steps.buildx.outputs.name }}
  #         platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/386,linux/ppc64le,s390x
  #         push: true
  #         load: true
  #         context: .
  #         file: ./${{ matrix.version }}/${{ matrix.variant }}/Dockerfile
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:${{ matrix.version }}-${{ matrix.variant }}
  #
