name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      base_image:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        id: buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/386,linux/ppc64le,s390x
          push: true
          context: .
          file: ./${{ inputs.node_version }}/${{ inputs.base_image }}/Dockerfile
          tags: ${{ secrets.username }}/node:${{ inputs.node_version }}-${{ inputs.base_image }}

