name: build-image-wild

on:
  schedule:
    - cron:  '0 0,8,16 * * *'
  push:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

  pull_request:
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - genMatrix.js
      - ".github/workflows/build-test.yml"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [18,20]
        base: [alpine3.17,alpine3.18,bookworm-slim,bookworm,bullseye-slim,bullseye]
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        id: buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/386,linux/ppc64le,s390x
          push: true
          context: .
          file: ./${{ matrix.version }}/${{ matrix.base }}/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:${{ inputs.node_version }}-${{ inputs.base_image }}

